### ISSUE TITLE
unsearchable tags

### ISSUE THREAD

**Issue by knappa** [girder/item_tags#5]
Some tags seem to be unsearchable. In particular, those with colons. Screenshots from data.nutritionallungimmunity.org provided
![Screenshot_2020-09-15_14-13-28](https://user-images.githubusercontent.com/4730938/93264312-eea0bd00-f774-11ea-8f8e-ec8f26ace30b.png)
![Screenshot_2020-09-15_14-12-55](https://user-images.githubusercontent.com/4730938/93264314-eea0bd00-f774-11ea-90fa-63a26d8fc7bb.png)
Testing on a local girder installation with a filesystem asset store did not have the same issue with the colon. I also did not try the literal same tags.

**Comment by mgrauer** [comment]
@dchiquit could you take a look when you get a chance?

**Comment by knappa** [comment]
@mgrauer  @dchiquit  Any update on this?

**Comment by dchiquito** [comment]
@knappa This has been resolved and searching for `NLI:DOCUMENTATION` now gives results. The search was splitting queries on any non-alphanumerical instead of only whitespace.
